services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - app_tmp:/app/tmp
    ports:
      - '3333:3333'
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    command: >
      sh -c "node ace migration:fresh --force && node ace db:seed && node ./bin/server.js"

volumes:
  app_tmp:
    driver: local
